"""store media binaries

Revision ID: d21b10427c73
Revises: 5c1d3a655111
Create Date: 2025-11-10 16:31:59.714975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21b10427c73'
down_revision = '5c1d3a655111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
